### ISSUE TITLE
在代码 yarn dev  阶段报的这个无效参数是什么意思?

### ISSUE THREAD

**Issue by 382406852** [snowdreamtech/vue-nuxt-element-template#3]
![屏幕截图 2023-10-29 005923](https://github.com/snowdreamtech/vue-nuxt-element-template/assets/29084388/fca37282-4425-41f8-9911-2746644bfe6d)

我应该怎么去我应该怎么去修复他?

**Comment by snowdream** [comment]
请使用Pnpm替代Yarn试试。
